import { ChicaneThemeProvider } from '~/controllers/ThemeProvider'
import Header from '../components/sections/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-slate-200 to-slate-300 dark:bg-gradient-to-l dark:from-slate-800 dark:to-slate-900`} >
        <ChicaneThemeProvider >
          <Header />
          <main>{children}</main>
        </ChicaneThemeProvider>
      </body>
    </html >
  )
}

